//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentCamp.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoArtista
    {
        public int IdProductoArtista { get; set; }
        public int idProducto { get; set; }
        public int idArtista { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
